class char_class(character):
    def barbarian(player):
        # dostuff
    def bard(player):
        # dostuff
    def cleric(player):
        # dostuff
    def druid(player):
        # dostuff
    def fighter(player):
        # dostuff
    def monk(player):
        # dostuff
    def paladin(player):
        # dostuff
    def ranger(player):
        # dostuff
    def rogue(player):
        # dostuff
    def sorcerer(player):
        # dostuff
    def wizard(player):
        # dostuff
