from flask_wtf import Form
from wtforms import validators, StringField

class Skills(Form):
    acrobatics = StringField(u'acrobatics', validators=[validators.input_required()])
    appraise = StringField(u'appraise', validators=[validators.input_required()])
    bluff = StringField(u'bluff', validators=[validators.input_required()])
    climb = StringField(u'climb', validators=[validators.input_required()])
    craft_a = StringField(u'craft a', validators=[validators.input_required()])
    craft_b = StringField(u'craft b', validators=[validators.input_required()])
    craft_c = StringField(u'craft c', validators=[validators.input_required()])
    diplomacy = StringField(u'diplomacy', validators=[validators.input_required()])
    disable_device = StringField(u'disable device', validators=[validators.input_required()])
    disguise = StringField(u'disguise', validators=[validators.input_required()])
    escape_artist = StringField(u'escape artist', validators=[validators.input_required()])
    fly = StringField(u'fly', validators=[validators.input_required()])
    handle_animal = StringField(u'handle animal', validators=[validators.input_required()])
    heal = StringField(u'heal', validators=[validators.input_required()])
    intimidate = StringField(u'intimidate', validators=[validators.input_required()])
    knowledge_arcana = StringField(u'knowledge arcana', validators=[validators.input_required()])
    knowledge_dungeoneering = StringField(u'knowledge dungeoneering', validators=[validators.input_required()])
    knowledge_engineering = StringField(u'knowledge engineering', validators=[validators.input_required()])
    knowledge_geography = StringField(u'knowledge geography', validators=[validators.input_required()])
    knowledge_history = StringField(u'knowledge history', validators=[validators.input_required()])
    knowledge_local = StringField(u'knowledge local', validators=[validators.input_required()])
    knowledge_nature = StringField(u'knowledge nature', validators=[validators.input_required()])
    knowledge_nobility = StringField(u'knowledge nobility', validators=[validators.input_required()])
    knowledge_planes = StringField(u'knowledge planes', validators=[validators.input_required()])
    knowledge_religion = StringField(u'knowledge religion', validators=[validators.input_required()])
    linguistics = StringField(u'linguistics', validators=[validators.input_required()])
    perception = StringField(u'perception', validators=[validators.input_required()])
    perform_a = StringField(u'perform a', validators=[validators.input_required()])
    perform_b = StringField(u'perform b', validators=[validators.input_required()])
    profession_a = StringField(u'profession a', validators=[validators.input_required()])
    profession_b = StringField(u'profession b', validators=[validators.input_required()])
    ride = StringField(u'ride', validators=[validators.input_required()])
    sense_motive = StringField(u'sense motive', validators=[validators.input_required()])
    sleight_of_hand = StringField(u'sleight of hand', validators=[validators.input_required()])
    spellcraft = StringField(u'spellcraft', validators=[validators.input_required()])
    stealth = StringField(u'stealth', validators=[validators.input_required()])
    survival = StringField(u'survival', validators=[validators.input_required()])
    swim = StringField(u'swim', validators=[validators.input_required()])
    use_magic_device = StringField(u'use magic device', validators=[validators.input_required()])
